### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by oneezy** [trofrigo/polymer-theme#3]
I've followed your steps and I've almost got this working... But none of the data is showing.
Can you identify my problem from the screenshots below?

-----

## I've activated the new WP Rest API plugin:
![image](https://cloud.githubusercontent.com/assets/7369575/23668063/7e62aedc-0325-11e7-860b-601b2f3bcc65.png)

## Changed the permalink:
![image](https://cloud.githubusercontent.com/assets/7369575/23668132/c2149a00-0325-11e7-994d-1372c0b4a1bd.png)

## And created the Blog page:
![image](https://cloud.githubusercontent.com/assets/7369575/23668198/fe15d500-0325-11e7-9e74-d422a59e04ba.png)

**Comment by rodrigosancho** [comment]
I tried to get the same error in local. I think I fix it with last commit, so, give it a try and tell if it is working.

**Comment by oneezy** [comment]
Hey @trofrigo ,

I recorded a quick screencast showing you where I'm at now. I've managed to get the blog posts up, but all other pages I create are **404**.

Do you have any idea why?

**Video:**
https://drive.google.com/file/d/0ByR1kQvOUDJbaVpybXF4eXBwY3c/view

**Comment by rodrigosancho** [comment]
Hi @oneezy ,

First of all, I really appreciate the effort you are doing with this project and I want to help you making it working.

Watching your video, I realized that you are using wordpress under an alias called 'wordpress-backup'. I have never tried this before and it could be causing some 404 errors. Could you copy me any posible javascript error shown by your webbrowser?

For future versions, I was thinking about create an admin element and load it in wordpress's backoffice in order to config this kind of stuff.

**Comment by oneezy** [comment]
No problemo!
I've been looking for something like this so I'm happy to help.

Are you just using the alias `wordpress` ?  or something else?

---

Here's my 2nd video showing off the errors:
https://drive.google.com/file/d/0ByR1kQvOUDJbSUh3QXNGWHQ2cGc/view

**Comment by oneezy** [comment]
Forgot to mention, I'm using wordpress 4.7.3

Apparently you no longer need the WP REST API w/ this version upgrade.

**Comment by oneezy** [comment]
**Screeshot:**

![image](https://cloud.githubusercontent.com/assets/7369575/23815594/572acddc-05ae-11e7-9b09-0370ced8ca68.png)

**Comment by rodrigosancho** [comment]
As expected, was an alias problem. I've already fixed it in the last commit. 

From now on, a new global-variable is added into the index.php; 
 `<global-variable key="alias" value="/"></global-variable>`

That's the default behavior when the domain has not an alias. In your case, you should change it to:
 `<global-variable key="alias" value="/wordpress-backup/"></global-variable>`

This is one of those things that should be configured in the config element that I mentioned before. I hope it could be posible in a near future.

**Comment by oneezy** [comment]
Great work dude! 
I can confirm from this end that it's working flawlessly :grin:

I wouldn't have normally created a `wordpress-backup` or messed around w/ an alias..but when working locally on some windows machines, the `localhost` port that wamp server uses get's hijacked by a windows program (i read into it somewhere the other day). The work-around was to set a new port and create an alias for it.. but this in turn created a new problem :sweat:

But all in all, nice work man.

What all else do you have planned for this project?

**Comment by oneezy** [comment]
I spoke a little to soon here, but seeing as this is actually installing now, i'll leave this closed and create a new issue.
