### ISSUE TITLE
Browser Compatibility: Microsoft Edge Fails

### ISSUE THREAD

**Issue by oneezy** [trofrigo/polymer-theme#6]
Navigating to your [demo ](http://wp.trofrigo.me/)in the Microsoft Edge browser completely fails:

![image](https://cloud.githubusercontent.com/assets/7369575/24090621/e909a274-0d0f-11e7-9f50-67387b2e742c.png)

**Comment by rodrigosancho** [comment]
Hi @oneezy ,

I've already fix this issue in my last commit.
![edge](https://cloud.githubusercontent.com/assets/4243194/24217553/8c52f28c-0f40-11e7-9800-305c2eed74fc.PNG)

**Comment by oneezy** [comment]
Great!
What was the problem if you don't mind me asking?

**Comment by rodrigosancho** [comment]
I was treating the result of the `querySelectorAll() ` method as an iterable array, and it only works in Chrome. I have to change it `querySelectorAll(). forEach(callback) ` to `[].forEach.call(querySelectorAll(), callback) `

**Comment by oneezy** [comment]
ahhh, i see. Awesome.

I need to update to your new version.

I've been hacking away on the first theme, though it's mainly UI type stuff. Should be an easy transfer.

-----

Check it out! 
http://waifufightdangostyle.com/

**Comment by rodrigosancho** [comment]
Wow, it looks awesome! GJ

**Comment by oneezy** [comment]
hahA.. thanks @trofrigo 

I haven't even began to utilize wordpress yet, though I suppose that's a good thing in the beginning stages.  Save that for phase 2.
